feat: imagepullpolicy configuration for chart
keptn/lifecycle-toolkit-charts pull request #125
Opened 2024-01-16 09:02 UTC by prakrit55

* `imagePullPolicy` config in common chart as per https://github.com/keptn/lifecycle-toolkit/pull/2807

2024-01-16 09:04 UTC, prakrit55 commented
@RealAnna, configured the `imagePullPolicy` in common chart

2024-01-17 09:06 UTC, mowies requested changes
please also bump the common chart version to`0.1.2`

2024-01-17 10:39 UTC, prakrit55 commented
> please also bump the common chart version to`0.1.2`

sure

2024-01-17 11:53 UTC, mowies approved these changes

2024-01-17 11:53 UTC, merged